In [1]:
import numpy as np
print(np.__version__)

2.2.3


In [5]:
#Array Creation
list=[10,20,30,40,50]
arr = np.array(list)
print(arr)
print('Type:', type(arr))
print('Shape',arr.shape)

[10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Shape (5,)


arr1= np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)

In [9]:
arr1=np.zeros((2,3))
print(arr1)
print(arr1[0][1])

[[0. 0. 0.]
 [0. 0. 0.]]
0.0


In [10]:
arr2=np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr3=np.arange(1,10,3)
print(arr3)

[1 4 7]


In [14]:
sample=np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [16]:
arr3=np.arange(1,10,3)
arr4=np.arange(2,10,3)
print(arr3+arr4)
print(arr3*arr4)
print(arr3**2)

[ 3  9 15]
[ 2 20 56]
[ 1 16 49]


In [17]:
purchase=np.array([
    [200,150,100],
    [300,250,400],
    [100,200,150],
    [500,600,550],
    [50,80,100]
])
total_spend=purchase.sum(axis=1)
average_spend=purchase.mean(axis=1)
print("total:",total_spend)
print("average",average_spend)
    

total: [ 450  950  450 1650  230]
average [150.         316.66666667 150.         550.          76.66666667]


In [18]:
A=np.array([[2,3],[4,1]])
B=np.array([8,10])
solution=np.linalg.solve(A,B)
print("Solution(x,y):",solution)

Solution(x,y): [2.2 1.2]


In [19]:
sales = np.array([1000, 1800, 1500, 1100, 1900, 1500, 1950, 2000, 1750, 1400])
 
#total sales
total_sales = np.sum(sales)
#average sales
avg_sales = np.mean(sales)
#highest sales
highest_sales = np.max(sales)
#lowest sales
lowest_sales = np.min(sales)
print(f"Total Sales: {total_sales}")
print(f"Average Sales: {avg_sales}")
print(f"Highest Sales: {highest_sales}")
print(f"Lowest Sales: {lowest_sales}")

Total Sales: 15900
Average Sales: 1590.0
Highest Sales: 2000
Lowest Sales: 1000


In [20]:
import numpy as np
 
sales = np.array([1000, 1800, 1500, 1100, 1900, 1500, 1950, 2000, 1750, 1400])
 
#total sales
total_sales = np.sum(sales)
#average sales
avg_sales = np.mean(sales)
#highest sales
highest_sales = np.max(sales)
#lowest sales
lowest_sales = np.min(sales)
print(f"Total Sales: {total_sales}")
print(f"Average Sales: {avg_sales}")
print(f"Highest Sales: {highest_sales}")
print(f"Lowest Sales: {lowest_sales}")
#above the average
days_above_avg = np.where(sales > avg_sales)[0]
print(f"Days with sales above the average: {days_above_avg}")
#10% increase
increased_sales = sales * 1.10
print(f"Sales with 10% increase: {increased_sales}")

Total Sales: 15900
Average Sales: 1590.0
Highest Sales: 2000
Lowest Sales: 1000
Days with sales above the average: [1 4 6 7 8]
Sales with 10% increase: [1100. 1980. 1650. 1210. 2090. 1650. 2145. 2200. 1925. 1540.]


In [23]:
print("sales higher than average:",sales[sales>avg_sales])

sales higher than average: [1800 1900 1950 2000 1750]


In [24]:
updated=sales*1.1
print(updated)
print(sales)

[1100. 1980. 1650. 1210. 2090. 1650. 2145. 2200. 1925. 1540.]
[1000 1800 1500 1100 1900 1500 1950 2000 1750 1400]


In [25]:
print(np.sort(sales))

[1000 1100 1400 1500 1500 1750 1800 1900 1950 2000]


In [29]:
import pandas as pd
 
df = pd.read_csv('Store_data.csv')
 
print(df)

    order_id                         product   Category  Quantity  Price  \
0       1001                        LG KP130         LG         3   2698   
1       1002                      Celkon C99     Celkon         3  10219   
2       1003                   Panasonic X88  Panasonic         1  11735   
3       1004         Samsung M6710 Beat DISC    Samsung         3   6839   
4       1005                        Realme 5     Realme         4   7712   
5       1006   Samsung Galaxy S4 mini I9195I    Samsung         4   9462   
6       1007  Samsung Galaxy Xcover FieldPro    Samsung         2  10262   
7       1008                        LG G7120         LG         5   8026   
8       1009                     XOLO One HD       XOLO         1   8993   
9       1010               Yezz Billy 5S LTE       Yezz         3   2497   
10      1011                    verykool R80   verykool         3   6824   
11      1012                      Nokia 1209      Nokia         2   9333   
12      1013

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   order_id      20 non-null     int64 
 1   product       20 non-null     object
 2   Category      20 non-null     object
 3   Quantity      20 non-null     int64 
 4   Price         20 non-null     int64 
 5   Total_Amount  20 non-null     int64 
 6   Date          20 non-null     object
dtypes: int64(4), object(3)
memory usage: 1.2+ KB


In [31]:
df.isnull()

order_id  product  Category  Quantity  Price  Total_Amount   Date
0      False    False     False     False  False         False  False
1      False    False     False     False  False         False  False
2      False    False     False     False  False         False  False
3      False    False     False     False  False         False  False
4      False    False     False     False  False         False  False
5      False    False     False     False  False         False  False
6      False    False     False     False  False         False  False
7      False    False     False     False  False         False  False
8      False    False     False     False  False         False  False
9      False    False     False     False  False         False  False
10     False    False     False     False  False         False  False
11     False    False     False     False  False         False  False
12     False    False     False     False  False         False  False
13     False    False     False     False  False         False  False
14     False    False     False     False  False         False  False
15     False    False     False     False  False         False  False
16     False    False     False     False  False         False  False
17     False    False     False     False  False         False  False
18     False    False     False     False  False         False  False
19     False    False     False     False  False         False  False

In [32]:
df.fillna(0)

order_id                         product   Category  Quantity  Price  \
0       1001                        LG KP130         LG         3   2698   
1       1002                      Celkon C99     Celkon         3  10219   
2       1003                   Panasonic X88  Panasonic         1  11735   
3       1004         Samsung M6710 Beat DISC    Samsung         3   6839   
4       1005                        Realme 5     Realme         4   7712   
5       1006   Samsung Galaxy S4 mini I9195I    Samsung         4   9462   
6       1007  Samsung Galaxy Xcover FieldPro    Samsung         2  10262   
7       1008                        LG G7120         LG         5   8026   
8       1009                     XOLO One HD       XOLO         1   8993   
9       1010               Yezz Billy 5S LTE       Yezz         3   2497   
10      1011                    verykool R80   verykool         3   6824   
11      1012                      Nokia 1209      Nokia         2   9333   
12      1013                  alcatel OT 355    alcatel         2  10080   
13      1014                      Bird S1130       Bird         5   7381   
14      1015               Microsoft Kin One  Microsoft         2   5560   
15      1016                   verykool i410   verykool         4   7063   
16      1017              Nokia 3720 classic      Nokia         5   5974   
17      1018                  BLU Samba Mini        BLU         3   5928   
18      1019                   Motorola V188   Motorola         2   2051   
19      1020                      LG G Vista         LG         3   5140   

    Total_Amount        Date  
0              0   5/28/2024  
1              0   2/20/2024  
2              0   1/30/2025  
3              0    2/7/2025  
4              0   4/28/2024  
5              0   4/21/2024  
6              0    5/1/2024  
7              0  10/26/2024  
8              0   1/21/2025  
9              0    8/8/2024  
10             0   1/31/2025  
11             0   9/17/2024  
12             0    2/6/2025  
13             0    7/5/2024  
14             0   12/7/2024  
15             0  12/30/2024  
16             0    5/3/2024  
17             0   8/25/2024  
18             0   1/17/2025  
19             0   2/14/2024

In [33]:
type("hello")

str

In [34]:
import numpy as np
data=np.array([10,12,14,15,18,21,25,100])
Q1=np.percentile(data,25)
Q3=np.percentile(data,75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
outliers=data[(data<lower_bound)|(data>upper_bound)]
print("Outliers:",outliers)

Outliers: [100]
